version: '3.8'
services:
  web:
    image: nginx:1.25
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - swarm_services
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  swarm_services:
    external: true
