---
- name: 4. Deploy Nginx Service to Swarm Cluster (using shell module)
  hosts: swarm_manager
  become: true
  tasks:
    - name: Ensure nginx_web service is created or updated
      shell: >
        docker service inspect nginx_web >/dev/null 2>&1 &&
        docker service update --image nginx:latest --replicas 3 nginx_web ||
        docker service create --name nginx_web --replicas 3 --publish mode=ingress,published=80,target=80 nginx:latest
      register: service_create_result
      changed_when: "'overall progress' in service_create_result.stdout"