---
- name: Ensure prerequisite apt packages are present
  ansible.builtin.apt:
    name: "{{ docker_engine_apt_packages }}"
    state: present
    update_cache: yes

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_engine_repository.repo }}"
    state: present

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ docker_engine_user }}"
    groups: docker
    append: yes

- name: Install Docker Python SDK
  ansible.builtin.pip:
    name: "{{ docker_engine_python_packages }}"
    state: present
