---
- name: Ensure sample app overlay network exists
  community.docker.docker_network:
    name: swarm_services
    driver: overlay
    scope: swarm

- name: Deploy sample Spring Boot stack
  community.docker.docker_stack:
    name: sample_app
    state: present
    compose:
      - "{{ role_path }}/files/sample-app.yml"
    resolve_image: never
