- name: Directly Join Worker Nodes to Swarm
  hosts: manager # Target manager first to get token
  become: true
  tasks:
    - name: Ensure Swarm manager is initialized and get join token
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_host }}"
      register: swarm_init_result

    - name: Set worker join token fact
      set_fact:
        worker_join_token: "{{ swarm_init_result.swarm_facts.JoinTokens.Worker }}"

- name: Join Worker Nodes to Swarm cluster
  hosts: worker1,worker2 # Now target workers
  become: true
  tasks:
    - name: Join worker node to Swarm cluster
      community.docker.docker_swarm:
        state: join
        join_token: "{{ hostvars['manager']['worker_join_token'] }}"
        remote_addrs: [ "{{ hostvars['manager']['ansible_host'] }}:2377" ]